### ISSUE TITLE
Game Switcher not working quite right with 3.2.0.

### ISSUE THREAD

**Issue by devanteweary** [spruceUI/spruceOS#282]
Before today, Game Switcher was pretty much perfect. Snappy, more or less instant, and just worked.

Now since I updated today, it's acting weird.  
For instance, I'm in the main menu and holding down vibrates the A30 but brings up the "Refresh Roms, Search" menu.

So then I go into Recents list and try again and it blanks the screen, the kicks out to the main menu and doesn't really do anything else.  
So then I try again and this time the Game Switcher works.

So then I load a game and the game loads fine. So then I try holding the home key again and it blanks out and spits me back into the main Spruce menu.

I load the game again and try and this time it seems to work.

So it's just kinda working/not working.

**Comment by Sundownersport** [comment]
We have replicated this issue and will begin working on it. Thank you for pointing it out!

**Comment by Sundownersport** [comment]
We figured it out and swapped out the release files. This issue has been fixed for all users going forward for 3.2.

thanks again for finding it!!!!

**Comment by XanXic** [comment]
Like Sun said this was put into the current release version, just because it's so new and we know only 100 people got it. It was mostly an issue related to joystick sending inputs. So be sure to go to settings (On the main menu) and run "calibrate joystick"

If you wish to reinstall 3.2.0 easily to get the quick fix, go to Advanced Settings app and look for "Allow a reinstall" task and turn that on and save. (If you don't see this task make sure the 'show expert settings' toggle is on). After that the OTA app should be shown with a "Check for Update" message. Run that and it'll detect you want to redownload 3.2.0 and install it.

**Comment by devanteweary** [comment]
Hey guys looks like the reinstall worked and the Switcher works much better. 
Still having a small issue where if I go into a game for the first time, then try the switcher, it'll open the Miyoo game menu. Then if I select Exit, it'll show the Switcher with the correct screenshot. So it's like it's quicksaving but still showing the menu instead.

Also, maybe it's me but I think it takes a couple seconds longer now for the Hold action.

Otherwise seems to be working fine.
